@echo off
echo Starting Redis Server...
start "Redis Server" /min "D:\Node\VSP\redis\redis-server.exe"

echo Waiting for Redis to initialize...
timeout /t 2 /nobreak >nul

echo Starting Development Server...
npm run dev
